jobs:
  - name: run tw stock monitor
    command: python /root/TWStockNotifier/main.py tw /root/TWStockNotifier/config.json
    shell: /bin/sh
    schedule: "* 9 * * 1-5"
    timezone: Asia/Taipei
  - name: run us stock monitor
    command: python /root/TWStockNotifier/main.py us /root/TWStockNotifier/config.json
    shell: /bin/sh
    schedule: "30 9 * * 1-5"
    timezone: America/New_York
