defaults:
    concurrencyPolicy: Forbid
jobs:
  - name: run tw stock monitor
    command: python /root/StockNotifier/main.py tw /root/StockNotifier/config.json
    shell: /bin/sh
    schedule: "0 9 * * 1-5"
    timezone: Asia/Taipei
  - name: run us stock monitor
    command: python /root/StockNotifier/main.py us /root/StockNotifier/config.json
    shell: /bin/sh
    schedule: "30 9 * * 1-5"
    timezone: America/New_York
